var i18n = $.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "MMddyyyy",
            "fulldayshow": "L d yyyy",
            "fulldayvalue": "M/d/yyyy",
            "Md": "W M/d",
            "Md3": "L d",
            "separator": "/",
            "year_index": 2,
            "month_index": 0,
            "day_index": 1,
            "day": "d",
            "sun": "Вос",
            "mon": "Пон",
            "tue": "Вто",
            "wed": "Сре",
            "thu": "Чет",
            "fri": "Пят",
            "sat": "Суб",
            "jan": "Янв",
            "feb": "Фер",
            "mar": "Мар",
            "apr": "Апр",
            "may": "Май",
            "jun": "Июн",
            "jul": "Июл",
            "aug": "Авг",
            "sep": "Сен",
            "oct": "Окт",
            "nov": "Ноя",
            "dec": "Дек"
        },
        "no_implemented": "No implemented yet",
        "to_date_view": "Щелкни чтобы уведитель текущую дату",
        "i_undefined": "Неопределено",
        "allday_event": "Ежедневная задача",
        "repeat_event": "Повторять задачу",
        "time": "Время",
        "event": "Задача",
        "location": "Нахождение",
        "participant": "Participant",
        "get_data_exception": "Exception when getting data",
        "new_event": "Новая задача",
        "confirm_delete_event": "Вы точно хотите удалить эту задачу? ",
        "confrim_delete_event_or_all": "Do you want to all repeat events or only this event? \r\nClick [OK] to delete only this event, click [Cancel] delete all events",
        "data_format_error": "Data format error! ",
        "invalid_title": "Event title can not be blank or contains ($<>)",
        "view_no_ready": "View is not ready",
        "example": "e.g., meeting at room 107",
        "content": "Что",
        "create_event": "Создать задачу",
        "update_detail": "Редактировать детали",
        "click_to_detail": "Смотреть детали",
        "i_delete": "Удалить",
        "day_plural": "дней",
        "others": "Другое",
        "item": ""
    }
});
